import { NextRequest } from 'next/server';
import { ApiResponseHelper } from '@/utils/http/response';
import { verifyToken } from '@/middlewares/auth/verifyToken';
import { checkRole } from '../../../../../middlewares/rbac/checkRole';
import { supabaseAdmin } from '@/lib/supabase/admin';
import crypto from 'crypto';

/**
 * GET: Fetches all active referral tracking links generated by the session affiliate.
 * Accessible via: GET /api/v1/affiliate/links
 */
export async function GET(req: NextRequest) {
  try {
    // 1. RBAC Check: Ensure user is logged in and holds proper affiliate permissions
    const user = await verifyToken(req);
    if (!user) {
      return ApiResponseHelper.unauthorized('Invalid or expired authentication session.');
    }

    const hasClearance = checkRole(user.role || 'buyer', ['affiliate', 'admin']);
    if (!hasClearance) {
      return ApiResponseHelper.forbidden('Access denied. Affiliate registration required.');
    }

    // 2. Gather matching referral link parameters from the database registry
    const { data: links, error } = await supabaseAdmin
      .from('affiliate_links')
      .select('*')
      .eq('user_id', user.id)
      .order('created_at', { ascending: false });

    if (error) {
      return ApiResponseHelper.badRequest('Failed to extract active affiliate links maps.');
    }

    return ApiResponseHelper.success(links || [], 'Affiliate link structures resolved successfully.');
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : 'Affiliate registry lookup failure.';
    return ApiResponseHelper.badRequest(message);
  }
}

/**
 * POST: Generates a unique secure referral link token tied to a specific digital asset.
 * Accessible via: POST /api/v1/affiliate/links
 */
export async function POST(req: NextRequest) {
  try {
    // 1. Authorization Shield
    const user = await verifyToken(req);
    if (!user) {
      return ApiResponseHelper.unauthorized('Session validation broken.');
    }

    const hasClearance = checkRole(user.role || 'buyer', ['affiliate', 'admin']);
    if (!hasClearance) {
      return ApiResponseHelper.forbidden('Access denied. Only certified affiliates can generate tracking nodes.');
    }

    const body = await req.json();
    const { productId } = body;

    if (!productId || typeof productId !== 'string') {
      return ApiResponseHelper.badRequest('A valid target productId string parameter is required.');
    }

    // 2. Anti-Duplicate Check: Prevent generating multiple tracks for the exact same asset item
    const { data: existingLink } = await supabaseAdmin
      .from('affiliate_links')
      .select('id, code')
      .eq('user_id', user.id)
      .eq('product_id', productId)
      .maybeSingle();

    if (existingLink) {
      return ApiResponseHelper.success(existingLink, 'An active tracking node already exists for this digital asset.', 200);
    }

    // 3. Cryptographic Token Generation: Mint a short unique alphanumeric tracking slug
    const customSlug = crypto.randomBytes(4).toString('hex').toUpperCase(); // e.g., "AF7B39E1"
    const trackingCode = `TMV-${user.id.slice(0, 4)}-${customSlug}`;

    // 4. Atomic ledger entry creation
    const { data: newLink, error: insertError } = await supabaseAdmin
      .from('affiliate_links')
      .insert([
        {
          user_id: user.id,
          product_id: productId,
          code: trackingCode,
          clicks: 0,
          conversions: 0,
          created_at: new Date().toISOString()
        }
      ])
      .select()
      .single();

    if (insertError || !newLink) {
      throw new Error('Database transaction collapsed during affiliate link registration.');
    }

    return ApiResponseHelper.success(newLink, 'New secure affiliate tracking channel initialized successfully.', 201);
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : 'Failed to initialize tracking node.';
    return ApiResponseHelper.badRequest(message);
  }
}